# Generated by Django 4.2.7 on 2023-11-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_record_reg_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Reg_No',
            new_name='Registration',
        ),
    ]
